{
  "artifacts": [],
  "command": "main",
  "experiment": {
    "base_dir": "G:\\\u7f51\u7edc\u7684\u6a21\u578b\\SiamFC-TensorFlow-master",
    "dependencies": [
      "numpy==1.14.0",
      "sacred==0.7.4",
      "tensorflow==1.5.0"
    ],
    "mainfile": "train_siamese_model.py",
    "name": "SiamFC-3s-color-scratch",
    "repositories": [],
    "sources": [
      [
        "SiamFC_utils\\__init__.py",
        "_sources\\__init___d41d8cd98f00b204e9800998ecf8427e.py"
      ],
      [
        "SiamFC_utils\\misc_utils.py",
        "_sources\\misc_utils_72b59981b744ae2c09c7187de2e26f39.py"
      ],
      [
        "configuration.py",
        "_sources\\configuration_f2ba72f3fbe8a15c4e256306163a492e.py"
      ],
      [
        "siamese_model.py",
        "_sources\\siamese_model_c52f9ffd02736cb31f80436d36bbea97.py"
      ],
      [
        "train_siamese_model.py",
        "_sources\\train_siamese_model_caa3aaef33581581cdeb11299b11f779.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"E:\\Anaconda\\lib\\site-packages\\sacred\\config\\captured_function.py\", line 46, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"G:/\u7f51\u7edc\u7684\u6a21\u578b/SiamFC-TensorFlow-master/train_siamese_model.py\", line 104, in main\n    model.build()\n",
    "  File \"G:\\\u7f51\u7edc\u7684\u6a21\u578b\\SiamFC-TensorFlow-master\\siamese_model.py\", line 212, in build\n    self.build_inputs()\n",
    "  File \"G:\\\u7f51\u7edc\u7684\u6a21\u578b\\SiamFC-TensorFlow-master\\siamese_model.py\", line 60, in build_inputs\n    self.dataloader = DataLoader(self.data_config, self.is_training())\n",
    "  File \"G:\\\u7f51\u7edc\u7684\u6a21\u578b\\SiamFC-TensorFlow-master\\datasets\\dataloader.py\", line 56, in __init__\n    self.dataset_py = VID(config['input_imdb'], config['max_frame_dist'])\n",
    "  File \"G:\\\u7f51\u7edc\u7684\u6a21\u578b\\SiamFC-TensorFlow-master\\datasets\\vid.py\", line 55, in __init__\n    with open(imdb_path, 'rb') as f:\n",
    "FileNotFoundError: [Errno 2] No such file or directory: 'data/train_imdb.pickle'\n"
  ],
  "heartbeat": "2019-01-19T01:33:23.929245",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz",
    "hostname": "DESKTOP-O6L6JOH",
    "os": [
      "Windows",
      "Windows-10-10.0.17134-SP0"
    ],
    "python_version": "3.6.4"
  },
  "meta": {
    "command": "main",
    "options": {
      "--beat_interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print_config": false,
      "--priority": null,
      "--queue": false,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2019-01-19T01:33:23.783723",
  "status": "FAILED",
  "stop_time": "2019-01-19T01:33:23.937228"
}